name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Enable Debug Logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Debug - Check Docker Version
        run: docker --version

      - name: Debug - Check Secrets Availability
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then echo "DOCKER_USERNAME is missing!"; exit 1; fi
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then echo "DOCKER_PASSWORD is missing!"; exit 1; fi
          echo "All required secrets are set."

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Debug - List Files in Directory
        run: ls -la

      - name: Build Docker Image
        run: docker build -t sumitdev99/reactjs-app .

      - name: Debug - Show Built Docker Images
        run: docker images

      - name: Publish Image to Docker Hub
        run: docker push sumitdev99/reactjs-app:latest
      - name: Debug - Check Build Directory
        run: ls -la ./dist || echo "⚠️ dist folder is missing!"

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from docker hub
        run: docker pull sumitdev99/reactjs-app:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer sumitdev99/reactjs-app
